baseurl = "/"
languageCode = "en-us"
theme = "hello-friend"
paginate = 1
tags = ["Django", "JavaScript"]

[params]
  contentTypeName = "posts"
  # "light" or "dark"
  defaultTheme = "light"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 5
  showReadingTime = true

[languages]
  [languages.en]
    title = "Mohd. Shafikur Rahman"
    subtitle = ""
    keywords = ""
    copyright = "@ Mohd. Shafikur Rahman"
    menuMore = "Show more"
    writtenBy = "Written by"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "Mon, Jan 2, 2006"

    [languages.en.params.logo]
      logoText = "shafikshaon-home"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts"
        weight= 1
      [[languages.en.menu.main]]
        identifier = "me"
        name = "Me"
        url = "/me"
        weight= 2
      [[languages.en.menu.main]]
        identifier = "contact"
        name = "Contact"
        url = "/contact"
        weight= 3